version: '2'

volumes:
  nvidia:
    external:
      name: nvidia_driver_367.57
  shared:

services:
  jupyter:
    build: ./docker
    volumes:
      - ./notebooks:/notebooks
      - ./models:/models
      - ../../cristian/tensorbuilder:/tensorbuilder
      - ../../cristian/phi:/phi
      - shared:/logs
      - nvidia:/usr/local/nvidia:ro
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    ports:
      - "8888:8888"
    command: bash -c "cd /phi && pip install -e . && cd /tensorbuilder && pip install -e . && cd /notebooks && /run_jupyter.sh"

  tensorboard:
    build: ./docker
    volumes:
      - shared:/logs
      - nvidia:/usr/local/nvidia:ro
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    ports:
      - "6006:6006"
    command: bash -c "rm -fr /logs/* && tensorboard --logdir=/logs"
